language: node_js
node_js:
  - 0.10

env:
  global:
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
    - LOGS_DIR=/tmp/angular-build/logs

before_script:
  - mkdir -p $LOGS_DIR
  - ./node_modules/protractor/scripts/sauce_connect_setup.sh
  - npm install -g bower
  - bower install angular angular-route
  - ./node_modules/protractor/scripts/wait_for_browser_provider.sh
